---
- name: Deploy Ecomm Web Application
  hosts: n1
  become: yes
 
  tasks:
  - name: Install Git
    yum:
      name: git
      state: present

  - name: Host Code
    git:
      repo: https://github.com/Aramide-star/ecomm-3.git
      dest: /var/www/html  
...


