---
- name: Install HTTP Server
  hosts: g1
  become: yes

  tasks:

    - name: Install HTTPD on Amazon Linux
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: Start and enable HTTPD on Amazon Linux
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Amazon"

    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Apache2 on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
