---
- name: Install HTTP Sever
  hosts: g1
  become: yes
 
  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: present      
      when: ansible_distribution == "Amazon"

  - name: Start HTTPD
    service:
      name: httpd
      state: started
      enabled: yes
      when: ansible_distribution == "Amazon"
    
  - name: enable httpd
    service:
      name: httpd
      enabled: yes
      when: ansible_distribution == "Amazon"
      
  - name: Install Apache2
    apt:
      name: apache2
      state: present      
      when: ansible_distribution == "Ubuntu"

  - name: Start Apache2
    service:
        name: apache2
        state: started
        enabled: yes
        when: ansible_distribution == "Ubuntu"

  - name: enable apache2
    service:
        name: apache2
        enabled: yes
        when: ansible_distribution == "Ubuntu"
...


