---
- name: Configure Web Server with Static and Dynamic Pages
  hosts:
    - g1
    - g2
  become: yes

  vars:
    page_title: "Welcome to My Website"
    header: "Hello, World!"
    body: "This is a sample web page created using Ansible."

  tasks:
    - name: Copy static HTML file to web server directory
      copy:
        src: static.html
        dest: /var/www/html/static.html
      when: ansible_distribution in ["Ubuntu", "Debian", "RedHat", "CentOS", "Amazon"]

    - name: Copy dynamic HTML file to web server directory
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
      when: ansible_distribution in ["Ubuntu", "Debian", "RedHat", "CentOS", "Amazon"]
